export { default as ErrorIc } from './ErrorIc'
export { default as MenuIc } from './MenuIc'
export { default as OrderIc } from './OrderIc'
export { default as UsersIc } from './UsersIc'
export * from './VerticalDotsIc'
export { default as flavourIc } from './flavourIc'
