export enum Types {
  FRUTALES = 'FRUTALES',
  ESPECIALES = 'ESPECIALES',
  DE_LA_CASA = 'DE LA CASA',
  CUBIERTA = 'CUBIERTA',
  TOPPING = 'TOPPING'
}

export enum OrderStates {
  ON_STANDBY = 'EN ESPERA',
  IN_PREPARATION = 'EN PREPARACION',
  COMPLETE = 'PREPARADO',
  MODIFY = 'MODIFICADO',
  CANCEL = 'CANCELADO'
}
